"""adding cover_pic to playlists

Revision ID: 1f05cce73af3
Revises: 
Create Date: 2018-04-16 11:11:05.948344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f05cce73af3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('pictureURL', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'pictureURL')
    # ### end Alembic commands ###
